# 로컬용 application.yml

spring:
  profiles:
    active: local
  application:
    name: pocketco
  # .env 파일 인식하게끔
  config:
    import: optional:file:.env[.properties]
  # mysql
  datasource:
    url: jdbc:mysql://localhost:3306/pocketco?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    format_sql: true
  #redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}


# jwt
jwt:
  secret: ${JWT_SECRET}                  # 필수(반드시 환경변수로만)

# Swagger config
springdoc:
  packages-to-scan: com.pocketco
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

storage:
  local:
    base-dir: pocketco/uploads

app:
  public-base-url: http://localhost:8080

# fire base
firebase:
  credentials-path: ${FIREBASE_FILE_PATH}

# Judge0
judge0:
  base-url: ${JUDGE0_BASE_URL}