# ===================================  공통 application.yml ===================================
spring:
  profiles:
    active: local   # 기본 실행은 local
  application:
    name: pocketco

  # redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

# jwt
jwt:
  secret: ${JWT_SECRET}

# swagger config
springdoc:
  packages-to-scan: com.pocketco
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

# fire base
firebase:
  credentials-path: ${FIREBASE_FILE_PATH}

# judge0
judge0:
  base-url: ${JUDGE0_BASE_URL}
  authn-token: ${JUDGE0_AUTHN_TOKEN}

# ============================================ local ============================================
---
spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]     # .env 파일 인식

  # mySQL
  datasource:
    url: jdbc:mysql://localhost:3306/pocketco?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

# local 이미지 저장
storage:
  local:
    base-dir: pocketco/uploads

app:
  public-base-url: http://localhost:8080

springdoc:
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

# ============================================ prod ============================================
---
spring:
  config:
    activate:
      on-profile: prod

  # rds - mySQL
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/pocketco?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

  # aws
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

# s3
storage:
  s3:
    bucket: ${S3_BUCKET}
    region: ${AWS_REGION}
    base-url: https://${S3_BUCKET}.s3.${AWS_REGION}.amazonaws.com

# swagger
springdoc:
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    enabled: true